<div class="copyright">
   <section class="copyright">All content copyright <a href="{{config.root}}">{{config.title}}</a> &copy; 
   {% if theme.since and theme.since != current %} {{ theme.since }}{% endif %}{{ current }} &bull;<span class="author">{{ config.author }}</span>&bull; All rights reserved.</section>
   <section class="powered-by">Proudly published with <a class="icon-ghost" href="http://zespia.tw/hexo/">Hexo</a></section>
</div>

{% block footer %}{% endblock %}